[package]
name = "ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
gm_helper_corelibrary = {path = '../gm_helper_corelibrary'}
rand = "0.8.5"
sqlite = "0.31.0"
